services:
  db:
    image: postgres:16
    container_name: shelfapp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shelfapp
      POSTGRES_USER: shelfapp_user
      POSTGRES_PASSWORD: shelfapp_pass
    ports:
      - "5432:5432"
    volumes:
      - shelfapp_pgdata:/var/lib/postgresql/data

volumes:
  shelfapp_pgdata:
